######################################################################
# Automatically generated by qmake (2.01a) Di. Mrz 17 18:13:56 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tree.h
SOURCES += main.cpp tree.cpp
CONFIG += console
