######################################################################
# Automatically generated by qmake (2.01a) Di. Mrz 17 15:55:32 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += thread.cpp
CONFIG += console
