######################################################################
# Automatically generated by qmake (2.01a) Mi. Mrz 18 15:18:07 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
