######################################################################
# Automatically generated by qmake (2.01a) Mi. Mrz 18 15:18:22 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += QtBeispiel.h window.h Zeichenflaeche.h
SOURCES += main.cpp
