######################################################################
# Automatically generated by qmake (2.01a) Mi. Mrz 18 15:19:07 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Window.h
SOURCES += main.cpp
