# Compiliert alle .cpp-Dateien im aktuellen Verzeichnis, und zwar
# jede für sich, d.h. jede Datei muß eine main-Funktion enthalten
# -fno-elide-constructors sorgt dafür, dass Kopierkonstruktor-
# aufrufe nicht wegoptimiert werden (um sie hier protokollieren zu können)
include ../../make/mf_alle44
CXXFLAGS += -O3 -fno-elide-constructors


