######################################################################
# Automatically generated by qmake (2.01a) Mi. Mrz 18 15:17:16 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DialogUser.h NamenDialog.h
SOURCES += main.cpp
