
makeall:
	$(MAKE) -C array2d
	$(MAKE) -C boost
	$(MAKE) -C blitz
	@echo Ausfuehrung mit make runadd  oder make runmult

runadd:
	array2d/add.exe
	boost/addboost.exe
	blitz/addblitz.exe

runmult:
	array2d/mult.exe
	boost/multboost.exe
	blitz/multblitz.exe

clean:


