all:
	$(MAKE) -C k18/tdd
	$(MAKE) -C k18/datum
	$(MAKE) -C k6/variadicTemplate
	$(MAKE) -C k6/rekursiveTemplates
	$(MAKE) -C k6/meinstringOpt
	$(MAKE) -C k6/stack
	$(MAKE) -C k6/numobj
	$(MAKE) -C k6/meinstring
	$(MAKE) -C k21
	$(MAKE) -C k15/http/server
	$(MAKE) -C k15/http/get
	$(MAKE) -C k15/tcpsocket/zeit
	$(MAKE) -C k15/tcpsocket/bidirectional
	$(MAKE) -C k15/udpsocket
	$(MAKE) -C k15/host
	$(MAKE) -C k29
	$(MAKE) -C k8/speicher
	$(MAKE) -C k8/logik
	$(MAKE) -C k8/stream
	$(MAKE) -C k17
	$(MAKE) -C k27/pair
	$(MAKE) -C k27/forward
	$(MAKE) -C k27/tuple
	$(MAKE) -C k27/move
	$(MAKE) -C k27/bind
	$(MAKE) -C k27/binaryfunc
	$(MAKE) -C k10/strstream
	$(MAKE) -C k10
	$(MAKE) -C k9/rational
	$(MAKE) -C k9/funktor
	$(MAKE) -C k9/smartptr
	$(MAKE) -C k9/vektor
	$(MAKE) -C k9/datum
	$(MAKE) -C k9/new/eigene
	$(MAKE) -C k9/new/malloc
	$(MAKE) -C k9/new/waechter
	$(MAKE) -C k9/new/new
	$(MAKE) -C k9/new/zaehlend
	$(MAKE) -C k9/poly
	$(MAKE) -C k9/matrix
	$(MAKE) -C k9/mathvek
	$(MAKE) -C k2
	$(MAKE) -C k23/staticLib/libprojekt
	$(MAKE) -C k23/staticLib/anwendung
	$(MAKE) -C k23/dynLib/libprojekt
	$(MAKE) -C k23/dynLib/anwendung
	$(MAKE) -C k23/abhaengigkeiten
	$(MAKE) -C k23/dirTreeRec
	$(MAKE) -C k23/templateInst/inklusion
	$(MAKE) -C k23/templateInst/trennIFimpl
	$(MAKE) -C k23/templateInst/extern
	$(MAKE) -C k23/dirTree
	$(MAKE) -C k23/verzTrennung
	$(MAKE) -C k22/bewegCtor
	$(MAKE) -C k22/optimPlusOp
	$(MAKE) -C k25/datum
	$(MAKE) -C k25/tabelle
	$(MAKE) -C k25/files/boost/tree
	$(MAKE) -C k25/files/boost
	$(MAKE) -C k25/files
	$(MAKE) -C k25/binaer
	$(MAKE) -C k28/list/identify
	$(MAKE) -C k28/list
	$(MAKE) -C k28/vector/auto
	$(MAKE) -C k28/vector
	$(MAKE) -C k28/emplace
	$(MAKE) -C k28
	$(MAKE) -C k1
	$(MAKE) -C k5/array2d
	$(MAKE) -C k5
	$(MAKE) -C loesungen/k6/1
	$(MAKE) -C loesungen/k6/3
	$(MAKE) -C loesungen/k6/2
	$(MAKE) -C loesungen/k9/1_bis_4
	$(MAKE) -C loesungen/k9/8_bis_13
	$(MAKE) -C loesungen/k9/14_15
	$(MAKE) -C loesungen/k9/6_7
	$(MAKE) -C loesungen/k2
	$(MAKE) -C loesungen/k28
	$(MAKE) -C loesungen/k1
	$(MAKE) -C loesungen/k5
	$(MAKE) -C loesungen/k3/8
	$(MAKE) -C loesungen/k3/9
	$(MAKE) -C loesungen/k3/10
	$(MAKE) -C loesungen/k3
	$(MAKE) -C loesungen/k4/3
	$(MAKE) -C loesungen/k4/6
	$(MAKE) -C loesungen/k4/4
	$(MAKE) -C loesungen/k4
	$(MAKE) -C loesungen/k13/1
	$(MAKE) -C loesungen/k30
	$(MAKE) -C loesungen/k24/1
	$(MAKE) -C loesungen/k24/3
	$(MAKE) -C loesungen/k24/2
	$(MAKE) -C loesungen/k11
	$(MAKE) -C loesungen/k7/3
	$(MAKE) -C loesungen/k7/2
	$(MAKE) -C loesungen/k7/4_5
	$(MAKE) -C k31/geld
	$(MAKE) -C k31/datum
	$(MAKE) -C k31
	$(MAKE) -C k12/regextester
	$(MAKE) -C k3
	$(MAKE) -C k4/ort1
	$(MAKE) -C k4/ratio
	$(MAKE) -C k4/delegierenderKonstruktor
	$(MAKE) -C k4
	$(MAKE) -C k16
	$(MAKE) -C k13/rwp
	$(MAKE) -C k13/rw
	$(MAKE) -C k13/prodcons
	$(MAKE) -C k13/workerthread
	$(MAKE) -C k13
	$(MAKE) -C k24/textverarbeitung/regex
	$(MAKE) -C k24/textverarbeitung
	$(MAKE) -C k24/vermischtes/regex
	$(MAKE) -C k24/vermischtes/copy
	$(MAKE) -C k24/vermischtes
	$(MAKE) -C k24/folgen
	$(MAKE) -C k24/random
	$(MAKE) -C k24/vergleich
	$(MAKE) -C k24/strings/boost
	$(MAKE) -C k24/strings
	$(MAKE) -C k24/complex
	$(MAKE) -C k24/sortieren
	$(MAKE) -C k24/array2dmath/performancetest/blitz
	$(MAKE) -C k24/array2dmath/performancetest/boost
	$(MAKE) -C k24/array2dmath/performancetest/array2d
	$(MAKE) -C k24/array2dmath/performancetest
	$(MAKE) -C k24/array2dmath
	$(MAKE) -C k24/heap
	$(MAKE) -C k24/array2d
	$(MAKE) -C k24/mengen
	$(MAKE) -C k24/finden
	$(MAKE) -C k33/placement
	$(MAKE) -C k33/uniqueptr
	$(MAKE) -C k33/sharedptr
	$(MAKE) -C k33/weakptr
	$(MAKE) -C k33/arraysharedptr
	$(MAKE) -C k11/einf
	$(MAKE) -C k11/liste
	$(MAKE) -C k34
	$(MAKE) -C k7/abstrakt
	$(MAKE) -C k7/erben
	$(MAKE) -C k7/privat
	$(MAKE) -C k7/mehrfach/konflikt
	$(MAKE) -C k7/mehrfach/virtual
	$(MAKE) -C k7/mehrfach
	$(MAKE) -C k7
clean:
	$(MAKE) -C k18/tdd clean
	$(MAKE) -C k18/datum clean
	$(MAKE) -C k6/variadicTemplate clean
	$(MAKE) -C k6/rekursiveTemplates clean
	$(MAKE) -C k6/meinstringOpt clean
	$(MAKE) -C k6/stack clean
	$(MAKE) -C k6/numobj clean
	$(MAKE) -C k6/meinstring clean
	$(MAKE) -C k21 clean
	$(MAKE) -C k15/http/server clean
	$(MAKE) -C k15/http/get clean
	$(MAKE) -C k15/tcpsocket/zeit clean
	$(MAKE) -C k15/tcpsocket/bidirectional clean
	$(MAKE) -C k15/udpsocket clean
	$(MAKE) -C k15/host clean
	$(MAKE) -C k29 clean
	$(MAKE) -C k8/speicher clean
	$(MAKE) -C k8/logik clean
	$(MAKE) -C k8/stream clean
	$(MAKE) -C k17 clean
	$(MAKE) -C k27/pair clean
	$(MAKE) -C k27/forward clean
	$(MAKE) -C k27/tuple clean
	$(MAKE) -C k27/move clean
	$(MAKE) -C k27/bind clean
	$(MAKE) -C k27/binaryfunc clean
	$(MAKE) -C k10/strstream clean
	$(MAKE) -C k10 clean
	$(MAKE) -C k9/rational clean
	$(MAKE) -C k9/funktor clean
	$(MAKE) -C k9/smartptr clean
	$(MAKE) -C k9/vektor clean
	$(MAKE) -C k9/datum clean
	$(MAKE) -C k9/new/eigene clean
	$(MAKE) -C k9/new/malloc clean
	$(MAKE) -C k9/new/waechter clean
	$(MAKE) -C k9/new/new clean
	$(MAKE) -C k9/new/zaehlend clean
	$(MAKE) -C k9/poly clean
	$(MAKE) -C k9/matrix clean
	$(MAKE) -C k9/mathvek clean
	$(MAKE) -C k2 clean
	$(MAKE) -C k23/staticLib/libprojekt clean
	$(MAKE) -C k23/staticLib/anwendung clean
	$(MAKE) -C k23/dynLib/libprojekt clean
	$(MAKE) -C k23/dynLib/anwendung clean
	$(MAKE) -C k23/abhaengigkeiten clean
	$(MAKE) -C k23/dirTreeRec clean
	$(MAKE) -C k23/templateInst/inklusion clean
	$(MAKE) -C k23/templateInst/trennIFimpl clean
	$(MAKE) -C k23/templateInst/extern clean
	$(MAKE) -C k23/dirTree clean
	$(MAKE) -C k23/verzTrennung clean
	$(MAKE) -C k22/bewegCtor clean
	$(MAKE) -C k22/optimPlusOp clean
	$(MAKE) -C k25/datum clean
	$(MAKE) -C k25/tabelle clean
	$(MAKE) -C k25/files/boost/tree clean
	$(MAKE) -C k25/files/boost clean
	$(MAKE) -C k25/files clean
	$(MAKE) -C k25/binaer clean
	$(MAKE) -C k28/list/identify clean
	$(MAKE) -C k28/list clean
	$(MAKE) -C k28/vector/auto clean
	$(MAKE) -C k28/vector clean
	$(MAKE) -C k28/emplace clean
	$(MAKE) -C k28 clean
	$(MAKE) -C k1 clean
	$(MAKE) -C k5/array2d clean
	$(MAKE) -C k5 clean
	$(MAKE) -C loesungen/k6/1 clean
	$(MAKE) -C loesungen/k6/3 clean
	$(MAKE) -C loesungen/k6/2 clean
	$(MAKE) -C loesungen/k9/1_bis_4 clean
	$(MAKE) -C loesungen/k9/8_bis_13 clean
	$(MAKE) -C loesungen/k9/14_15 clean
	$(MAKE) -C loesungen/k9/6_7 clean
	$(MAKE) -C loesungen/k2 clean
	$(MAKE) -C loesungen/k28 clean
	$(MAKE) -C loesungen/k1 clean
	$(MAKE) -C loesungen/k5 clean
	$(MAKE) -C loesungen/k3/8 clean
	$(MAKE) -C loesungen/k3/9 clean
	$(MAKE) -C loesungen/k3/10 clean
	$(MAKE) -C loesungen/k3 clean
	$(MAKE) -C loesungen/k4/3 clean
	$(MAKE) -C loesungen/k4/6 clean
	$(MAKE) -C loesungen/k4/4 clean
	$(MAKE) -C loesungen/k4 clean
	$(MAKE) -C loesungen/k13/1 clean
	$(MAKE) -C loesungen/k30 clean
	$(MAKE) -C loesungen/k24/1 clean
	$(MAKE) -C loesungen/k24/3 clean
	$(MAKE) -C loesungen/k24/2 clean
	$(MAKE) -C loesungen/k11 clean
	$(MAKE) -C loesungen/k7/3 clean
	$(MAKE) -C loesungen/k7/2 clean
	$(MAKE) -C loesungen/k7/4_5 clean
	$(MAKE) -C k31/geld clean
	$(MAKE) -C k31/datum clean
	$(MAKE) -C k31 clean
	$(MAKE) -C k12/regextester clean
	$(MAKE) -C k3 clean
	$(MAKE) -C k4/ort1 clean
	$(MAKE) -C k4/ratio clean
	$(MAKE) -C k4/delegierenderKonstruktor clean
	$(MAKE) -C k4 clean
	$(MAKE) -C k16 clean
	$(MAKE) -C k13/rwp clean
	$(MAKE) -C k13/rw clean
	$(MAKE) -C k13/prodcons clean
	$(MAKE) -C k13/workerthread clean
	$(MAKE) -C k13 clean
	$(MAKE) -C k24/textverarbeitung/regex clean
	$(MAKE) -C k24/textverarbeitung clean
	$(MAKE) -C k24/vermischtes/regex clean
	$(MAKE) -C k24/vermischtes/copy clean
	$(MAKE) -C k24/vermischtes clean
	$(MAKE) -C k24/folgen clean
	$(MAKE) -C k24/random clean
	$(MAKE) -C k24/vergleich clean
	$(MAKE) -C k24/strings/boost clean
	$(MAKE) -C k24/strings clean
	$(MAKE) -C k24/complex clean
	$(MAKE) -C k24/sortieren clean
	$(MAKE) -C k24/array2dmath/performancetest/blitz clean
	$(MAKE) -C k24/array2dmath/performancetest/boost clean
	$(MAKE) -C k24/array2dmath/performancetest/array2d clean
	$(MAKE) -C k24/array2dmath/performancetest clean
	$(MAKE) -C k24/array2dmath clean
	$(MAKE) -C k24/heap clean
	$(MAKE) -C k24/array2d clean
	$(MAKE) -C k24/mengen clean
	$(MAKE) -C k24/finden clean
	$(MAKE) -C k33/placement clean
	$(MAKE) -C k33/uniqueptr clean
	$(MAKE) -C k33/sharedptr clean
	$(MAKE) -C k33/weakptr clean
	$(MAKE) -C k33/arraysharedptr clean
	$(MAKE) -C k11/einf clean
	$(MAKE) -C k11/liste clean
	$(MAKE) -C k34 clean
	$(MAKE) -C k7/abstrakt clean
	$(MAKE) -C k7/erben clean
	$(MAKE) -C k7/privat clean
	$(MAKE) -C k7/mehrfach/konflikt clean
	$(MAKE) -C k7/mehrfach/virtual clean
	$(MAKE) -C k7/mehrfach clean
	$(MAKE) -C k7 clean
